name = "BioJuliaTemplate"
uuid = "0294bc8e-4aa2-4248-b79e-9c1e4efe5058"
authors = ["YourName <YourEmail>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
julia = "1.11"

[targets]
test = ["Test"]
